In [5]:
from google.colab import files
files.upload()

Saving CGPA.csv to CGPA.csv

{'CGPA.csv': b'StudyHours,Attendance,CGPA\n4.37,61.26,2.9\n9.56,85.46,5.12\n7.59,72.57,4.29\n6.39,80.34,3.88\n2.4,96.3,3.52\n2.4,69.97,2.71\n1.52,76.42,2.25\n8.8,90.22,5.08\n6.41,69.15,3.61\n7.37,63.08,4.13\n1.19,71.59,2.52\n9.73,66.45,4.58\n8.49,97.19,5.18\n2.91,92.32,3.3\n2.64,85.34,3.16\n2.65,94.86,3.57\n3.74,92.15,3.42\n5.72,67.46,3.41\n4.89,95.7,3.7\n3.62,81.57,3.05\n6.51,92.3,4.28\n2.26,95.84,3.16\n3.63,72.72,3.1\n4.3,64.4,3.24\n5.1,69.12,3.42\n8.07,77.08,4.75\n2.8,92.72,3.14\n5.63,94.43,4.62\n6.33,60.28,3.73\n1.42,80.43,2.36\n6.47,76.7,3.76\n2.53,68.88,2.73\n1.59,64.79,2.23\n9.54,73.5,4.97\n9.69,97.72,5.46\n8.28,72.93,4.43\n3.74,80.75,3.07\n1.88,88.12,2.52\n7.16,74.55,4.05\n4.96,98.87,4.14\n2.1,98.5,3.14\n5.46,70.07,3.29\n1.31,79.89,2.53\n9.18,72.04,4.77\n3.33,71.39,2.75\n6.96,61.48,3.85\n3.81,84.38,3.34\n5.68,80.11,3.58\n5.92,62.06,3.59\n2.66,71.15,2.83\n9.73,96.33,5.56\n7.98,69.58,4.5\n9.46,65.8,4.38\n9.05,79.58,4.62\n6.38,99.43,4.51\n9.3,69.68,4.79\n1.8,86.89,2.88\n2.76,90.46,3.91\n1.41,69.51,2.43\n3.93,89.13,3.69\n4.5,74.71,3.54\n3.44,85.29,3.37\n8.46,85.34,4.68\n4.21,81.43,3.54\n3.53,63.61,2.68\n5.88,93.41,4.08\n2.27,72.83,2.54\n8.22,67.46,4.33\n1.67,61.63,2.7\n9.88,83.64,4.76\n7.95,87.1,4.76\n2.79,60.66,2.23\n1.05,80.48,2.33\n8.34,69.06,4.6\n7.36,85.81,4.44\n7.56,66.97,3.89\n7.94,87.64,4.49\n1.67,75.47,2.65\n4.23,97.47,3.57\n2.04,65.5,2.47\n8.77,73.64,4.61\n6.61,64.54,3.64\n3.98,96.99,4.06\n1.57,95.09,3.0\n3.8,70.32,2.64\n3.93,86.4,3.44\n7.57,92.69,4.49\n6.74,82.21,4.34\n8.98,81.19,4.66\n5.25,69.67,3.45\n2.08,63.72,2.5\n7.42,95.89,4.82\n7.85,96.02,4.54\n6.05,85.32,3.95\n7.94,73.56,4.26\n5.44,73.97,3.48\n5.7,89.04,4.34\n4.85,95.88,3.95\n1.23,95.48,2.53\n1.97,91.2,3.1\n'}

In [10]:
import numpy as np
import pandas as pd

In [11]:
df = pd.read_csv('CGPA.csv')
df

    StudyHours  Attendance  CGPA
0         4.37       61.26  2.90
1         9.56       85.46  5.12
2         7.59       72.57  4.29
3         6.39       80.34  3.88
4         2.40       96.30  3.52
..         ...         ...   ...
95        5.44       73.97  3.48
96        5.70       89.04  4.34
97        4.85       95.88  3.95
98        1.23       95.48  2.53
99        1.97       91.20  3.10

[100 rows x 3 columns]

In [23]:
X = df.iloc[:,0:1]
y = df.iloc[:,1:2]

In [21]:
X

    StudyHours
0         4.37
1         9.56
2         7.59
3         6.39
4         2.40
..         ...
95        5.44
96        5.70
97        4.85
98        1.23
99        1.97

[100 rows x 1 columns]

In [24]:
y

    Attendance
0        61.26
1        85.46
2        72.57
3        80.34
4        96.30
..         ...
95       73.97
96       89.04
97       95.88
98       95.48
99       91.20

[100 rows x 1 columns]

In [25]:
X.shape
y.shape

(100, 1)

In [26]:

from sklearn.model_selection import train_test_split

In [27]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [28]:
print(X_train.shape)
print(X_test.shape)

(80, 1)
(20, 1)

In [29]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [30]:
reg.fit(X_train,y_train)

LinearRegression()

In [31]:
y_pred=reg.predict(X_test)

In [32]:
from sklearn.metrics import r2_score

In [33]:
r2_score(y_test,y_pred)

-0.038959511585377804

In [34]:
reg.coef_

array([[0.05850666]])

In [35]:
reg.intercept_

array([79.16145328])

In [36]:
class MeraLR:

    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)

        # calcuate the coeffs
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]

    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred

In [37]:
lr = MeraLR()
lr.fit(X_train,y_train)

In [38]:
X_train.shape

(80, 1)

In [39]:
np.insert(X_train,0,1,axis=1).shape

(80, 2)

In [40]:
y_pred = lr.predict(X_test)

In [41]:
r2_score(y_test,y_pred)

-0.03895951158537603

In [42]:
lr.coef_

array([[0.05850666]])

In [43]:
lr.intercept_

array([79.16145328])

In [58]:

from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [59]:
X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [46]:
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [47]:
df.shape

(100, 3)

In [48]:
df.head()

   feature1  feature2      target
0  0.627630  0.902444   72.394335
1 -0.288310  1.447150   49.789291
2  1.241154  1.055107  123.821733
3  0.460255 -0.930339   76.169942
4 -1.749961 -1.046133 -162.947412

In [ ]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.show()